[package]
name = "waggle"
version = "0.1.0"
authors = ["wyglea"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = { path = "lib-gl" }
glutin = "0.24.1"
takeable-option = "0.5"
